name: DEPLOY
on:
  push:
    branches:
    - dev
    - main
jobs: 
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          yarn
          yarn run build:dev 
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzhe ssh --progress --delete
        path: dist/
        remote_path: /home/didelofr/public_html/lilian-dev
        remote_host: didelo.fr
        remote_user: didelofr
        remote_key: ${{ secrets.SSH_KEY }}

  build_and_deploy_preprod:
    needs: [build_and_deploy_dev]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          yarn
          yarn run build:preprod 
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzhe ssh --progress --delete
        path: dist/
        remote_path: /home/didelofr/public_html/lilian-preprod
        remote_host: didelo.fr
        remote_user: didelofr
        remote_key: ${{ secrets.SSH_KEY }}

  build_and_deploy_prod:
    needs: [build_and_deploy_preprod]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          yarn
          yarn run build:prod 
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzhe ssh --progress --delete
        path: dist/
        remote_path: /home/didelofr/public_html/lilian-prod
        remote_host: didelo.fr
        remote_user: didelofr
        remote_key: ${{ secrets.SSH_KEY }}